# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 07 Jan 2022 20:34:47 +0000
*               @ALL          0
*               @user         8
