# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 07 Jan 2022 20:34:47 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$yBZ6TRyW6dGJAErMN6MLtO7kVLKHN3uYaskEhYuO3B0z2rRKZ6Fei:Ralph-Rainer Welzel:ralph.welzel@gmail.com:admin,user
